// flow-typed signature: 3967fff442afbf2a5b0c2c4b6efb8517
// flow-typed version: <<STUB>>/babel-plugin-async-to-promises_v^1.0.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-async-to-promises'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-async-to-promises' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-async-to-promises/kneden/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/lib/ifrefactor' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/lib/looprefactor' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/lib/promisechain' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/lib/refactor' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/lib/utils' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/array-expr-exec-order/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/array-expr-exec-order/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/await-func-call/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/await-func-call/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/await-inside-await/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/await-inside-await/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/binary-expr-exec-order/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/binary-expr-exec-order/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/call-expr-exec-order/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/call-expr-exec-order/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/complex-loop/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/complex-loop/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/complex-trycatch/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/complex-trycatch/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/dowhile-loop/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/dowhile-loop/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/empty-func/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/empty-func/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/for-in-with-external-var/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/for-in-with-external-var/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/for-in/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/for-in/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/for-loop/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/for-loop/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/guard/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/guard/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/if-flow/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/if-flow/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/keep-function-names-in-object-values/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/keep-function-names-in-object-values/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/lazy-op/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/lazy-op/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/loop-with-labels/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/loop-with-labels/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/nested-if-with-else/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/nested-if-with-else/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/nested-try-finally/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/nested-try-finally/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/no-block/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/no-block/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-conditional/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-conditional/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-loop/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-loop/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-nested-expr/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-nested-expr/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-sequence-expr/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-sequence-expr/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-trycatch/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/normal-trycatch/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/object-expr-exec-order/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/object-expr-exec-order/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/pouchdb-auth/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/pouchdb-auth/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/resp-name-reserved/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/resp-name-reserved/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/return-in-loop/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/return-in-loop/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/sequence-expr/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/sequence-expr/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/simple-conditional/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/simple-conditional/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/simple-nested-if/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/simple-nested-if/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/simple-switch/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/simple-switch/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/switch/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/switch/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/ternary-expr/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/ternary-expr/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/this-arguments/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/this-arguments/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch-finally/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch-finally/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/this-arguments/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/this-arguments/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-finally/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/try-finally/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/while-loop/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/fixtures/while-loop/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-async-to-promises/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-async-to-promises/kneden/index.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/kneden/index'>;
}
declare module 'babel-plugin-async-to-promises/lib/ifrefactor.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/lib/ifrefactor'>;
}
declare module 'babel-plugin-async-to-promises/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/lib/index'>;
}
declare module 'babel-plugin-async-to-promises/lib/looprefactor.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/lib/looprefactor'>;
}
declare module 'babel-plugin-async-to-promises/lib/promisechain.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/lib/promisechain'>;
}
declare module 'babel-plugin-async-to-promises/lib/refactor.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/lib/refactor'>;
}
declare module 'babel-plugin-async-to-promises/lib/utils.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/lib/utils'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/array-expr-exec-order/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/array-expr-exec-order/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/array-expr-exec-order/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/array-expr-exec-order/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/await-func-call/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/await-func-call/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/await-func-call/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/await-func-call/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/await-inside-await/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/await-inside-await/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/await-inside-await/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/await-inside-await/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/binary-expr-exec-order/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/binary-expr-exec-order/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/binary-expr-exec-order/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/binary-expr-exec-order/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/call-expr-exec-order/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/call-expr-exec-order/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/call-expr-exec-order/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/call-expr-exec-order/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/complex-loop/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/complex-loop/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/complex-loop/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/complex-loop/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/complex-trycatch/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/complex-trycatch/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/complex-trycatch/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/complex-trycatch/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/dowhile-loop/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/dowhile-loop/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/dowhile-loop/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/dowhile-loop/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/empty-func/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/empty-func/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/empty-func/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/empty-func/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/for-in-with-external-var/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/for-in-with-external-var/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/for-in-with-external-var/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/for-in-with-external-var/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/for-in/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/for-in/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/for-in/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/for-in/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/for-loop/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/for-loop/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/for-loop/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/for-loop/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/guard/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/guard/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/guard/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/guard/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/if-flow/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/if-flow/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/if-flow/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/if-flow/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/keep-function-names-in-object-values/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/keep-function-names-in-object-values/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/keep-function-names-in-object-values/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/keep-function-names-in-object-values/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/lazy-op/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/lazy-op/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/lazy-op/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/lazy-op/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/loop-with-labels/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/loop-with-labels/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/loop-with-labels/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/loop-with-labels/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/nested-if-with-else/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/nested-if-with-else/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/nested-if-with-else/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/nested-if-with-else/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/nested-try-finally/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/nested-try-finally/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/nested-try-finally/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/nested-try-finally/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/no-block/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/no-block/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/no-block/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/no-block/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-conditional/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-conditional/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-conditional/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-conditional/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-loop/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-loop/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-loop/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-loop/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-nested-expr/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-nested-expr/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-nested-expr/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-nested-expr/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-sequence-expr/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-sequence-expr/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-sequence-expr/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-sequence-expr/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-trycatch/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-trycatch/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/normal-trycatch/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/normal-trycatch/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/object-expr-exec-order/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/object-expr-exec-order/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/object-expr-exec-order/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/object-expr-exec-order/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/pouchdb-auth/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/pouchdb-auth/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/pouchdb-auth/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/pouchdb-auth/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/resp-name-reserved/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/resp-name-reserved/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/resp-name-reserved/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/resp-name-reserved/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/return-in-loop/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/return-in-loop/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/return-in-loop/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/return-in-loop/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/sequence-expr/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/sequence-expr/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/sequence-expr/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/sequence-expr/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/simple-conditional/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/simple-conditional/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/simple-conditional/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/simple-conditional/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/simple-nested-if/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/simple-nested-if/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/simple-nested-if/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/simple-nested-if/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/simple-switch/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/simple-switch/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/simple-switch/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/simple-switch/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/switch/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/switch/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/switch/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/switch/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/ternary-expr/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/ternary-expr/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/ternary-expr/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/ternary-expr/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/this-arguments/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/this-arguments/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/this-arguments/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/this-arguments/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch-finally/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-catch-finally/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch-finally/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-catch-finally/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-catch/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-catch/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/this-arguments/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-catch/this-arguments/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-catch/this-arguments/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-catch/this-arguments/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-finally/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-finally/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/try-finally/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/try-finally/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/while-loop/actual.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/while-loop/actual'>;
}
declare module 'babel-plugin-async-to-promises/test/fixtures/while-loop/expected.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/fixtures/while-loop/expected'>;
}
declare module 'babel-plugin-async-to-promises/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-async-to-promises/test/index'>;
}
