// flow-typed signature: eac240767d5a8ab52246b588850f3d38
// flow-typed version: <<STUB>>/fecha_v^2.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fecha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fecha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fecha/fecha' {
  declare module.exports: any;
}

declare module 'fecha/fecha.min' {
  declare module.exports: any;
}

declare module 'fecha/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fecha/fecha.js' {
  declare module.exports: $Exports<'fecha/fecha'>;
}
declare module 'fecha/fecha.min.js' {
  declare module.exports: $Exports<'fecha/fecha.min'>;
}
declare module 'fecha/test.js' {
  declare module.exports: $Exports<'fecha/test'>;
}
