// flow-typed signature: 00c80a3396aba8ee468a6a2c1386b15e
// flow-typed version: <<STUB>>/inferno-redux_v^1.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-redux/inferno-redux' {
  declare module.exports: any;
}

declare module 'inferno-redux/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-redux/inferno-redux.js' {
  declare module.exports: $Exports<'inferno-redux/inferno-redux'>;
}
declare module 'inferno-redux/src/index.js' {
  declare module.exports: $Exports<'inferno-redux/src/index'>;
}
