// flow-typed signature: 307d6eb0df448789bdb7858ab44dcd93
// flow-typed version: <<STUB>>/inferno-router_v^1.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-router/inferno-router' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/IndexLink' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/IndexRedirect' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/IndexRoute' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Link' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/match' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Redirect' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Route' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Router' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/RouterContext' {
  declare module.exports: any;
}

declare module 'inferno-router/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-router/inferno-router.js' {
  declare module.exports: $Exports<'inferno-router/inferno-router'>;
}
declare module 'inferno-router/lib/IndexLink.js' {
  declare module.exports: $Exports<'inferno-router/lib/IndexLink'>;
}
declare module 'inferno-router/lib/IndexRedirect.js' {
  declare module.exports: $Exports<'inferno-router/lib/IndexRedirect'>;
}
declare module 'inferno-router/lib/IndexRoute.js' {
  declare module.exports: $Exports<'inferno-router/lib/IndexRoute'>;
}
declare module 'inferno-router/lib/Link.js' {
  declare module.exports: $Exports<'inferno-router/lib/Link'>;
}
declare module 'inferno-router/lib/match.js' {
  declare module.exports: $Exports<'inferno-router/lib/match'>;
}
declare module 'inferno-router/lib/Redirect.js' {
  declare module.exports: $Exports<'inferno-router/lib/Redirect'>;
}
declare module 'inferno-router/lib/Route.js' {
  declare module.exports: $Exports<'inferno-router/lib/Route'>;
}
declare module 'inferno-router/lib/Router.js' {
  declare module.exports: $Exports<'inferno-router/lib/Router'>;
}
declare module 'inferno-router/lib/RouterContext.js' {
  declare module.exports: $Exports<'inferno-router/lib/RouterContext'>;
}
declare module 'inferno-router/src/index.js' {
  declare module.exports: $Exports<'inferno-router/src/index'>;
}
