// flow-typed signature: a8def6bcc9340e9c132753027d49ab17
// flow-typed version: <<STUB>>/inferno-server_v^1.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-server/inferno-server' {
  declare module.exports: any;
}

declare module 'inferno-server/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-server/inferno-server.js' {
  declare module.exports: $Exports<'inferno-server/inferno-server'>;
}
declare module 'inferno-server/src/index.js' {
  declare module.exports: $Exports<'inferno-server/src/index'>;
}
