// flow-typed signature: ea6885ff7ed2baff90914b617d222791
// flow-typed version: <<STUB>>/nodent-runtime_v^3.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodent-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodent-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodent-runtime/build' {
  declare module.exports: any;
}

declare module 'nodent-runtime/dist/index' {
  declare module.exports: any;
}

declare module 'nodent-runtime/runtime' {
  declare module.exports: any;
}

declare module 'nodent-runtime/tests/index' {
  declare module.exports: any;
}

declare module 'nodent-runtime/thenable' {
  declare module.exports: any;
}

declare module 'nodent-runtime/thenableFactory' {
  declare module.exports: any;
}

declare module 'nodent-runtime/zousan' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodent-runtime/build.js' {
  declare module.exports: $Exports<'nodent-runtime/build'>;
}
declare module 'nodent-runtime/dist/index.js' {
  declare module.exports: $Exports<'nodent-runtime/dist/index'>;
}
declare module 'nodent-runtime/runtime.js' {
  declare module.exports: $Exports<'nodent-runtime/runtime'>;
}
declare module 'nodent-runtime/tests/index.js' {
  declare module.exports: $Exports<'nodent-runtime/tests/index'>;
}
declare module 'nodent-runtime/thenable.js' {
  declare module.exports: $Exports<'nodent-runtime/thenable'>;
}
declare module 'nodent-runtime/thenableFactory.js' {
  declare module.exports: $Exports<'nodent-runtime/thenableFactory'>;
}
declare module 'nodent-runtime/zousan.js' {
  declare module.exports: $Exports<'nodent-runtime/zousan'>;
}
