// flow-typed signature: 896370ba88e58acb5ed3c3490f54ead3
// flow-typed version: <<STUB>>/postcss-modules-scope_v^1.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-scope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-scope' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-modules-scope/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-modules-scope/lib/index.js' {
  declare module.exports: $Exports<'postcss-modules-scope/lib/index'>;
}
