// flow-typed signature: 8c33131bb965ba0e0c078dbf45bd1d13
// flow-typed version: <<STUB>>/postcss-modules-extract-imports_v^1.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-extract-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-extract-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-modules-extract-imports/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-modules-extract-imports/lib/index.js' {
  declare module.exports: $Exports<'postcss-modules-extract-imports/lib/index'>;
}
