// flow-typed signature: 3e65b109eb928fa52b81245994fa4c44
// flow-typed version: <<STUB>>/postcss-modules-local-by-default_v^1.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-local-by-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-local-by-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-modules-local-by-default/index' {
  declare module.exports: $Exports<'postcss-modules-local-by-default'>;
}
declare module 'postcss-modules-local-by-default/index.js' {
  declare module.exports: $Exports<'postcss-modules-local-by-default'>;
}
